Telegram:
  #Bot Token
  token:
  #反代的Bot API 如https://xxx.xxx.com,不需要可留空
  APIAddr:
  #如果有Telegram贴纸预览服务,可在此写入,如 http://xx.xx.com,详情请参照 TGS_Preview 项目.
  TGSAddr:

bot:
  account:
  password:

Groups:
  #{QQ: QQ群号码, TG:Telegram Chat ID}
  - { QQ: , TG: }